/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

public class Main {
    public static void main(String... args) {
        TestLoggingInterface testLogging = Ioc.createTestLogging();
        testLogging.calculation4();
        System.out.println("\n");
        testLogging.calculation5();
        System.out.println("\n");
        testLogging.calculation(2);
        System.out.println("\n");
        testLogging.calculation(2, true);
        System.out.println("\n");
        testLogging.calculation2(2, true, 394857345L);
        System.out.println("\n");
        testLogging.calculation2(2, true, false);
        System.out.println("\n");
        testLogging.calculation3(2);
    }
}
