/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

public class Main {
    public static void main(String... args) {
        TestRunner runner = TestRunner.create(ClassTest.class);
        runner.run();
    }
}
