/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

/**
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 */
public class Main {
    public static void main(String... args) {
        TestRunner runner = TestRunner.create(ClassTest.class);
        runner.run();
    }
}
